#! /bin/bash

printf "which server(pi, ss, sss): "
read server
printf "file to copy: "
read fileName
if [ "$server" = "pi" ]; then
  server=192.168.0.72
  echo scp ${fileName} pi@${server}:/home/pi
  scp ${fileName} pi@${server}:/home/pi
else
  server=a${server}essmydeal.com
  echo scp -p 7822 ${fileName} chris@${server}:/home/chris/h
  scp -p 7822 ${fileName} chris@${server}:/home/chris/h
fi

