#! /bin/sh

job1=$(ps -ef | grep -v grep | grep "python server.py" | awk '{ print $2 }')
job2=$(ps -ef | grep -v grep | grep "python server2.py" | awk '{ print $2 }')
kill $job1
kill $job2

nohup python server.py &
nohup python server2.py &

sleep 3
ps -ef | grep -v grep | grep "python server.py"
ps -ef | grep -v grep | grep "python server2.py"

